#############################################################################
# Makefile for building: RoadDesignerQt
# Generated by qmake (2.01a) (Qt 4.7.4) on: Sun Jan 15 13:22:53 2012
# Project:  RoadDesignerQt/RoadDesignerQt.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile RoadDesignerQt/RoadDesignerQt.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -IRoadDesignerQt -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4 -I/usr/X11R6/include -I. -IRoadDesignerQt -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = RoadDesignerQt/main.cpp \
		RoadDesignerQt/mainwindow.cpp \
		Viewer.cpp \
		Vector.cpp \
		UI_Selectable.cpp \
		TwistLens.cpp \
		TriMeshTextured.cpp \
		RN_Vertex.cpp \
		RN_Intersection.cpp \
		RN_Edge.cpp \
		RN.cpp \
		OBJObject.cpp \
		ObjFile.cpp \
		ObjectManager.cpp \
		ModalMenu.cpp \
		LassoMenu.cpp \
		HeightMap.cpp \
		Collision.cpp \
		ClothoidSpline.cpp \
		CatmullRomSpline.cpp \
		Camera.cpp \
		BreakoutView.cpp \
		RoadDesignerQt/textureloader.cpp moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		Viewer.o \
		Vector.o \
		UI_Selectable.o \
		TwistLens.o \
		TriMeshTextured.o \
		RN_Vertex.o \
		RN_Intersection.o \
		RN_Edge.o \
		RN.o \
		OBJObject.o \
		ObjFile.o \
		ObjectManager.o \
		ModalMenu.o \
		LassoMenu.o \
		HeightMap.o \
		Collision.o \
		ClothoidSpline.o \
		CatmullRomSpline.o \
		Camera.o \
		BreakoutView.o \
		textureloader.o \
		moc_mainwindow.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		RoadDesignerQt/RoadDesignerQt.pro
QMAKE_TARGET  = RoadDesignerQt
DESTDIR       = 
TARGET        = RoadDesignerQt

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: RoadDesignerQt/RoadDesignerQt.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile RoadDesignerQt/RoadDesignerQt.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug -o Makefile RoadDesignerQt/RoadDesignerQt.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/RoadDesignerQt1.0.0 || $(MKDIR) .tmp/RoadDesignerQt1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/RoadDesignerQt1.0.0/ && $(COPY_FILE) --parents RoadDesignerQt/mainwindow.h Viewer.h Vector.h UI_Selectable.h TwistLens.h TriMeshTextured.h RN_Vertex.h RN_Intersection.h RN_Edge.h RN.h OBJObject.h ObjFile.h ObjectManager.h ModalMenu.h LassoMenu.h HeightMap.h Collision.h ClothoidSpline.h CatmullRomSpline.h Camera.h BreakoutView.h RoadDesignerQt/textureloader.h .tmp/RoadDesignerQt1.0.0/ && $(COPY_FILE) --parents RoadDesignerQt/main.cpp RoadDesignerQt/mainwindow.cpp Viewer.cpp Vector.cpp UI_Selectable.cpp TwistLens.cpp TriMeshTextured.cpp RN_Vertex.cpp RN_Intersection.cpp RN_Edge.cpp RN.cpp OBJObject.cpp ObjFile.cpp ObjectManager.cpp ModalMenu.cpp LassoMenu.cpp HeightMap.cpp Collision.cpp ClothoidSpline.cpp CatmullRomSpline.cpp Camera.cpp BreakoutView.cpp RoadDesignerQt/textureloader.cpp .tmp/RoadDesignerQt1.0.0/ && (cd `dirname .tmp/RoadDesignerQt1.0.0` && $(TAR) RoadDesignerQt1.0.0.tar RoadDesignerQt1.0.0 && $(COMPRESS) RoadDesignerQt1.0.0.tar) && $(MOVE) `dirname .tmp/RoadDesignerQt1.0.0`/RoadDesignerQt1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/RoadDesignerQt1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: Viewer.h \
		Vector.h \
		ModalMenu.h \
		RoadDesignerQt/textureloader.h \
		OBJObject.h \
		HeightMap.h \
		TriMeshTextured.h \
		ObjFile.h \
		Collision.h \
		UI_Selectable.h \
		Camera.h \
		RN.h \
		RN_Edge.h \
		ObjectManager.h \
		ClothoidSpline.h \
		CatmullRomSpline.h \
		RN_Intersection.h \
		TwistLens.h \
		BreakoutView.h \
		LassoMenu.h \
		RoadDesignerQt/mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) RoadDesignerQt/mainwindow.h -o moc_mainwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: RoadDesignerQt/main.cpp RoadDesignerQt/mainwindow.h \
		Viewer.h \
		Vector.h \
		ModalMenu.h \
		RoadDesignerQt/textureloader.h \
		OBJObject.h \
		HeightMap.h \
		TriMeshTextured.h \
		ObjFile.h \
		Collision.h \
		UI_Selectable.h \
		Camera.h \
		RN.h \
		RN_Edge.h \
		ObjectManager.h \
		ClothoidSpline.h \
		CatmullRomSpline.h \
		RN_Intersection.h \
		TwistLens.h \
		BreakoutView.h \
		LassoMenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o RoadDesignerQt/main.cpp

mainwindow.o: RoadDesignerQt/mainwindow.cpp RoadDesignerQt/mainwindow.h \
		Viewer.h \
		Vector.h \
		ModalMenu.h \
		RoadDesignerQt/textureloader.h \
		OBJObject.h \
		HeightMap.h \
		TriMeshTextured.h \
		ObjFile.h \
		Collision.h \
		UI_Selectable.h \
		Camera.h \
		RN.h \
		RN_Edge.h \
		ObjectManager.h \
		ClothoidSpline.h \
		CatmullRomSpline.h \
		RN_Intersection.h \
		TwistLens.h \
		BreakoutView.h \
		LassoMenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o RoadDesignerQt/mainwindow.cpp

Viewer.o: Viewer.cpp Viewer.h \
		Vector.h \
		ModalMenu.h \
		RoadDesignerQt/textureloader.h \
		OBJObject.h \
		HeightMap.h \
		TriMeshTextured.h \
		ObjFile.h \
		Collision.h \
		UI_Selectable.h \
		Camera.h \
		RN.h \
		RN_Edge.h \
		ObjectManager.h \
		ClothoidSpline.h \
		CatmullRomSpline.h \
		RN_Intersection.h \
		TwistLens.h \
		BreakoutView.h \
		LassoMenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Viewer.o Viewer.cpp

Vector.o: Vector.cpp Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Vector.o Vector.cpp

UI_Selectable.o: UI_Selectable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UI_Selectable.o UI_Selectable.cpp

TwistLens.o: TwistLens.cpp TwistLens.h \
		Vector.h \
		RN.h \
		RN_Edge.h \
		UI_Selectable.h \
		HeightMap.h \
		TriMeshTextured.h \
		RoadDesignerQt/textureloader.h \
		ObjFile.h \
		Collision.h \
		Camera.h \
		ObjectManager.h \
		ClothoidSpline.h \
		CatmullRomSpline.h \
		RN_Intersection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TwistLens.o TwistLens.cpp

TriMeshTextured.o: TriMeshTextured.cpp TriMeshTextured.h \
		RoadDesignerQt/textureloader.h \
		Vector.h \
		ObjFile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TriMeshTextured.o TriMeshTextured.cpp

RN_Vertex.o: RN_Vertex.cpp RN_Vertex.h \
		Vector.h \
		Collision.h \
		UI_Selectable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RN_Vertex.o RN_Vertex.cpp

RN_Intersection.o: RN_Intersection.cpp RN_Intersection.h \
		RN.h \
		RN_Edge.h \
		Vector.h \
		UI_Selectable.h \
		HeightMap.h \
		TriMeshTextured.h \
		RoadDesignerQt/textureloader.h \
		ObjFile.h \
		Collision.h \
		Camera.h \
		ObjectManager.h \
		ClothoidSpline.h \
		CatmullRomSpline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RN_Intersection.o RN_Intersection.cpp

RN_Edge.o: RN_Edge.cpp RN_Edge.h \
		Vector.h \
		UI_Selectable.h \
		HeightMap.h \
		TriMeshTextured.h \
		RoadDesignerQt/textureloader.h \
		ObjFile.h \
		Collision.h \
		Camera.h \
		RN.h \
		RN_Intersection.h \
		ObjectManager.h \
		ClothoidSpline.h \
		CatmullRomSpline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RN_Edge.o RN_Edge.cpp

RN.o: RN.cpp RN.h \
		RN_Edge.h \
		Vector.h \
		UI_Selectable.h \
		HeightMap.h \
		TriMeshTextured.h \
		RoadDesignerQt/textureloader.h \
		ObjFile.h \
		Collision.h \
		Camera.h \
		ObjectManager.h \
		ClothoidSpline.h \
		CatmullRomSpline.h \
		RN_Intersection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RN.o RN.cpp

OBJObject.o: OBJObject.cpp OBJObject.h \
		Vector.h \
		RoadDesignerQt/textureloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OBJObject.o OBJObject.cpp

ObjFile.o: ObjFile.cpp ObjFile.h \
		RoadDesignerQt/textureloader.h \
		Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ObjFile.o ObjFile.cpp

ObjectManager.o: ObjectManager.cpp ObjectManager.h \
		RN.h \
		RN_Edge.h \
		Vector.h \
		UI_Selectable.h \
		HeightMap.h \
		TriMeshTextured.h \
		RoadDesignerQt/textureloader.h \
		ObjFile.h \
		Collision.h \
		Camera.h \
		ClothoidSpline.h \
		CatmullRomSpline.h \
		RN_Intersection.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ObjectManager.o ObjectManager.cpp

ModalMenu.o: ModalMenu.cpp ModalMenu.h \
		Vector.h \
		RoadDesignerQt/textureloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ModalMenu.o ModalMenu.cpp

LassoMenu.o: LassoMenu.cpp LassoMenu.h \
		Vector.h \
		Collision.h \
		Viewer.h \
		ModalMenu.h \
		RoadDesignerQt/textureloader.h \
		OBJObject.h \
		HeightMap.h \
		TriMeshTextured.h \
		ObjFile.h \
		UI_Selectable.h \
		Camera.h \
		RN.h \
		RN_Edge.h \
		ObjectManager.h \
		ClothoidSpline.h \
		CatmullRomSpline.h \
		RN_Intersection.h \
		TwistLens.h \
		BreakoutView.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LassoMenu.o LassoMenu.cpp

HeightMap.o: HeightMap.cpp HeightMap.h \
		TriMeshTextured.h \
		RoadDesignerQt/textureloader.h \
		Vector.h \
		ObjFile.h \
		Collision.h \
		UI_Selectable.h \
		Camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HeightMap.o HeightMap.cpp

Collision.o: Collision.cpp Collision.h \
		Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Collision.o Collision.cpp

ClothoidSpline.o: ClothoidSpline.cpp ClothoidSpline.h \
		Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ClothoidSpline.o ClothoidSpline.cpp

CatmullRomSpline.o: CatmullRomSpline.cpp CatmullRomSpline.h \
		TriMeshTextured.h \
		RoadDesignerQt/textureloader.h \
		Vector.h \
		ObjFile.h \
		RN_Edge.h \
		UI_Selectable.h \
		HeightMap.h \
		Collision.h \
		Camera.h \
		RN.h \
		RN_Intersection.h \
		ObjectManager.h \
		ClothoidSpline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CatmullRomSpline.o CatmullRomSpline.cpp

Camera.o: Camera.cpp Camera.h \
		Vector.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Camera.o Camera.cpp

BreakoutView.o: BreakoutView.cpp BreakoutView.h \
		Camera.h \
		Vector.h \
		Collision.h \
		RN.h \
		RN_Edge.h \
		UI_Selectable.h \
		HeightMap.h \
		TriMeshTextured.h \
		RoadDesignerQt/textureloader.h \
		ObjFile.h \
		ObjectManager.h \
		ClothoidSpline.h \
		CatmullRomSpline.h \
		RN_Intersection.h \
		Viewer.h \
		ModalMenu.h \
		OBJObject.h \
		TwistLens.h \
		LassoMenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BreakoutView.o BreakoutView.cpp

textureloader.o: RoadDesignerQt/textureloader.cpp RoadDesignerQt/textureloader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o textureloader.o RoadDesignerQt/textureloader.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

